Add remove command to remove an alias

diff --git a/bin/gandi-aliases b/bin/gandi-aliases
--- a/bin/gandi-aliases
+++ b/bin/gandi-aliases
@@ -53,8 +53,9 @@ cmd_help() {
 Usage:
     $PROGRAM [-g|--get]
     $PROGRAM [-a|--add] <alias>
+    $PROGRAM [-r|--remove] <alias>
 
-  If no options are given, the default option is '--get'. Both commands retrive
+  If no options are given, the default option is '--help'. Both commands retrive
   the Gandi API key using 'pass'm to add and get aliases.
 
   This is a custom script, so it is tailored for my needings. Infact it uses
@@ -62,12 +63,16 @@ Usage:
 
 Available options:
     -g, --get
-        Retrieve the email aliases for $EMAIL and print
+        Retrieve the email aliases for '$EMAIL' and print
         them to stdout.
 
     -a, --add=alias
-        Add new alias for $EMAIL. It fails if the given
+        Add new alias for '$EMAIL'. It fails if the given
         alias is invalid or is a duplicate.
+
+    -r, --remove
+        Remove an alias from '$EMAIL'. It fails if the
+        given alias doesn't exist.
 
     -h, --help
         Show this message and exit.
@@ -95,7 +100,6 @@ cmd_get() {
 
 cmd_add() {
   [[ "$1" ]] || error "Missing alias to add for $EMAIL"
-
   local new_alias="$1"
 
   get_sensible_data
@@ -134,6 +138,47 @@ cmd_add() {
   fi
 }
 
+cmd_remove() {
+  [[ "$1" ]] || error "Missing alias to remove for $EMAIL"
+  local rm_alias="$1"
+
+  get_sensible_data
+
+  # Get the alias list.
+  local data
+  data="$(cmd_get)"
+  [[ "$?" == "0" ]] || error "$data"
+
+  [[ "$(echo "$data" | grep "$rm_alias")" ]] \
+    || error "Alias '$rm_alias' doesn't exist."
+
+  data="$(echo "$data" | jq ". -= [\"$rm_alias\"]" | jq '{ aliases: . }')"
+
+  # Remove the alias.
+  local reponse
+  response="$(curl --silent --show-error -X PATCH "$ENDPOINT" \
+                   -H "authorization: apikey $API_KEY" \
+                   -H "content-type: application/json" \
+                   -d "$data" 2>&1)"
+
+  [[ "$?" != "0" ]] && error "Failed to send PATCH request: $response"
+
+  [[ "$(echo "$response" | grep "error")" ]] \
+    && error "Failed to remove alias '$rm_alias' from '$EMAIL': $response"
+
+  sleep 5 # Because the changes are not immediate.
+
+  # Check if the alias is correctly removed.
+  data="$(cmd_get)"
+  [[ "$?" == "0" ]] || error "$data"
+
+  if [[ "$(echo "$data" | grep "$new_alias")" ]]; then
+    echo "Alias '$rm_alias' successfully removed from '$EMAIL'"
+  else
+    error "Failed to remove alias '$rm_alias' from '$EMAIL': $data"
+  fi
+}
+
 #
 # END subcommands functions
 #
@@ -142,10 +187,11 @@ PROGRAM="${0##*/}"
 COMMAND="$1"
 
 case "$1" in
-  -h|--help) shift; cmd_help "$@" ;;
-  -g|--get) shift;  cmd_get "$@" ;;
-  -a|--add) shift;  cmd_add "$@" ;;
-  *) shift;         cmd_help "$@" ;;
+  -h|--help) shift;   cmd_help "$@" ;;
+  -g|--get) shift;    cmd_get "$@" ;;
+  -a|--add) shift;    cmd_add "$@" ;;
+  -r|--remove) shift; cmd_remove "$@" ;;
+  *) shift;           cmd_help "$@" ;;
 esac
 
 exit 0
