Improve goodmorningitalia Bash script

diff --git a/bin/goodmorningitalia b/bin/goodmorningitalia
--- a/bin/goodmorningitalia
+++ b/bin/goodmorningitalia
@@ -1,61 +1,55 @@
 #!/usr/bin/env bash
 #
 # This script automatically subscribe a 30-days free trial on
-# goodmorningitalia.it, a online news service. I use to subscribe a temporary
-# email alias that forwards all emails to my personal inbox.
+# goodmorningitalia.it, an italian online news service. I use to subscribe a
+# temporary email alias that forwards all emails to my personal inbox.
 #
-# This script requires these programs:
-#   - wget: to do the connection (POST).
-#
-# WARNING: you need to activate you real email on jetable.org before run this
+# WARNING: you need to activate your real email on jetable.org before run this
 # script, also use this script may break ToS on both jetable.org and
 # goodmorningitalia.it!
+#
+# This script only requires 'curl'.
 #
 # Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>
 # All right reserved. This file is licensed under the MIT license.
 
 # It prints all arguments to the standard error and exits with error code 1.
 err() {
-  echo "$@" >&2
+  echo "ERROR: $*" >&2
   exit 1
 }
 
+readonly CURL_OPTS='--silent --show-error --location'
+
 # Temporary email creation.
 
-# To avoid SPAM.
-alias="newsletter-goodmorningitalia"
-domain="emanuelepetriglia.com"
-email="$alias@$domain"
+readonly JETABLE_URL='https://www.jetable.org/en/confirm'
+readonly EMAIL="newsletter-goodmorningitalia@emanuelepetriglia.com"
+readonly ONE_MONTH='2592000'
+readonly DATA="email=$EMAIL&time=$ONE_MONTH"
 
-readonly ONE_MONTH="2592000"
+# shellcheck disable=SC2086
+tmp_email="$(curl $CURL_OPTS "$JETABLE_URL" --data "$DATA" \
+  | grep --extended-regexp --only-matching '[0-9A-Za-z]+@jetable.org')"
 
-response="$(wget --output-document=- --quiet \
-  --post-data "email=$email&time=$ONE_MONTH" \
-  "https://www.jetable.org/en/confirm")"
+[[ "$tmp_email" ]] || err "Failed to create temporary email at $JETABLE_URL"
 
-tmp_email="$(echo "$response" | awk 'match($0, /<span id="aliasgenerated">(.*)<\/span>/, arr) { print arr[1] }')"
-
-if [[ ! "$tmp_email" =~ ([[:alnum:]])+@jetable.org ]]; then
-  err "Failed to create temporary email at https://www.jetable.org/en/index"
-else
-  echo "Temporary email for one month: $tmp_email"
-fi
+echo "Temporary email for one month: $tmp_email"
 
 # Subscription to goodmorningitalia.it
 
-readonly header='Content-Type: application/json;charset=utf-8'
-post_data=$(cat <<EOF
+readonly GOOD_URL='https://api.goodmorningitalia.it/auth'
+readonly HEADER='Content-Type: application/json'
+DATA=$(cat <<EOF
 {"action":"signup","email":"$tmp_email","nicename":"Mario","surName":"Rossi","giftUniqueKey":""}
 EOF
 )
+readonly DATA
 
-response="$(wget --quiet --output-document=- --header="$header" \
-  --post-data "$post_data" "https://api.goodmorningitalia.it/auth")"
+# shellcheck disable=SC2086
+response="$(curl $CURL_OPTS "$GOOD_URL" --header "$HEADER" --data "$DATA")"
 
-if [[ "$response" != '{"msg":"Success","status":1}' ]]; then
-  err "Failed to subscribe to https://app.goodmorningitalia.it/"
-fi
+[[ ! "$response" != '{"msg":"Success","status":1}' ]] \
+  || err "Failed to subscribe to https://app.goodmorningitalia.it/"
 
 echo "Success. Verify the new account on you email inbox!"
-
-exit 0
