Add a check command for Sapienza's Wifi
This new command checks if the login or logout are done succesfully.

diff --git a/bin/sapienza-wifi b/bin/sapienza-wifi
--- a/bin/sapienza-wifi
+++ b/bin/sapienza-wifi
@@ -2,11 +2,10 @@
 
 # This script logins automatically to the Sapienza's Wifi network, without open
 # a browser and insert manually the username and password.
-# It required Wget to do the request (POST) and pass to get the password.
+# It required `wget` to do the request (POST) and `pass` to get the password.
 
 # TODO:
 #   - Add error handling;
-#   - Check if the login is succesfully done.
 
 # Copyright (c) 2018 Emanuele Petriglia <inbox@emanuelepetriglia.me>
 # All right reserved. This file is licensed under the MIT license.
@@ -25,8 +24,37 @@ PASSWORD="$(pass $PASSWORD_LOCATION | head -n 1)"
 LOGOUT_ID_FILE="/tmp/sapienza-wifi-logout-id"
 
 #
+# BEGIN helper functions
+#
+
+# It prints all arguments to the standard error and exits with error code 1.
+error() {
+  echo "$@" >&2
+  exit 1
+}
+
+#
+# END helper functions
+#
+
+#
 # BEGIN subcommand functions
 #
+
+# It prints to the standard output "conncted" or "disconnected" if there is an
+# Internet connection or not.
+cmd_check_network() {
+  local test_page="https://www.uniroma1.it/"
+
+  wget --quiet --spider "$test_page"
+  local result=$?
+
+  if [[ $result -eq 0 ]]; then
+    echo "connected"
+  else
+    echo "disconnected"
+  fi
+}
 
 # It logins to the Sapienza's Wifi network, using the username and the password.
 # It also save in a temporary file the logout ID, it will be used to logout.
@@ -54,6 +82,10 @@ cmd_login() {
                                                      tail -n 1 > $LOGOUT_ID_FILE
 
   rm "$html_result"
+
+  if [[ $(cmd_check_network) != "connected" ]]; then
+    error "Failed to login"
+  fi
 }
 
 # It logouts from the Sapienza's Wifi network. It uses the ID provided by the
@@ -68,7 +100,11 @@ cmd_logout() {
 
   local data="$logout_id&$zone&$logout_command"
 
-  wget --quiet --post-data "$data" "$logout_url"
+  wget --quiet --output-document /dev/null --post-data "$data" "$logout_url"
+
+  if [[ $(cmd_check_network) != "disconnected" ]]; then
+    error "Failed to logout"
+  fi
 }
 
 #
@@ -81,6 +117,7 @@ COMMAND="$1"
 case "$1" in
   login)                cmd_login ;;
   logout)               cmd_logout ;;
+  check)                cmd_check_network;;
   *) COMMAND="login";   cmd_login ;;
 esac
 
